name: hybrid-malware-two
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - Flask
  - Flask-Cors
  - python-dotenv
  - mysql-connector-python
  - joblib
  - numpy
  - pandas
  - scikit-learn
  - xgboost
